# Generated by Django 4.2.19 on 2025-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
